name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: Gr1N/setup-poetry@v8 #install poetry
    - name: Install parts of toolchain 
      run: |
        python -m pip install --upgrade pip
    - name: Install requirements with poetry
      run: poetry install
    - name: Write key file
      env:
        CA_CERT: ${{ secrets.CA_CERT }}
        CA_KEY: ${{ secrets.CA_KEY }}
        CA_SIGNING_KEY: ${{ secrets.CA_SIGNING_KEY }}
      run: |
        echo "$CA_CERT" > ca-cert.pem
        echo "$CA_KEY" > ca-key.pem
        echo "$CA_SIGNING_KEY" > ca-signing-key.pem
    - name: Start poetry venv
      run: |
        poetry shell
    - name: Start the proxy
      run: |
        python3 ontologytimemachine/custom_proxy.py &    
    - name: Test with pytest
      run: |
        poetry run pytest -v
